### ISSUE TITLE
Error when processing payment

### ISSUE THREAD

**Issue by netzih** [rukykf/btcpay#4]
The keys and pairing seemed to have gone through successfully but when processing a payment I'm getting a PHP error as follows.

`Fatal error: Uncaught Error: Call to undefined method BTCPayServer\Client\Request::getSchema() in /httpdocs/wp-content/uploads/civicrm/ext/btcpay/vendor/btcpayserver/btcpayserver-php-client/src/BTCPayServer/Client/Request.php:181 Stack trace: #0 /httpdocs/wp-content/uploads/civicrm/ext/btcpay/vendor/btcpayserver/btcpayserver-php-client/src/BTCPayServer/Client/Request.php(91): BTCPayServer\Client\Request->getUriWithPort() #1 /httpdocs/wp-content/uploads/civicrm/ext/btcpay/CRM/Core/Payment/Btcpay.php(199): BTCPayServer\Client\Request->__toString() #2 /httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Contribute/Form/Contribution/Confirm.php(2838): CRM_Core_Payment_Btcpay->doPayment() #3 /httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Contribute/Form/Contribution/Confirm.php(2462): CRM_Contribute_Form_Contribution_Confirm->processConfirm() #4 /var/w in /httpdocs/wp-content/uploads/civicrm/ext/btcpay/vendor/btcpayserver/btcpayserver-php-client/src/BTCPayServer/Client/Request.php on line 181`

**Comment by netzih** [comment]
I am new to BTCpay.
Is it possible that this error was due to the BTCpay server node not being fully synched? 
It's a new server and just realized it taked time to synch up before it can be used.
I'm wondering if that's the issue and I just need to wait the 1-5 days for set up or is there something else I messed up?

**Comment by netzih** [comment]
Tested it with a fully synched BTCpay Server and it seemed to work fine.
So I am closing this issue for now. (assuming this issue is due to my server not being set up fully yet)
